### ISSUE TITLE
Parameter to skip updating certain packages

### ISSUE THREAD

**Issue by Trenly** [vedantmgoyal2009/winget-pkgs-automation#10]
**Describe the bug**
Balena.BalenaCLI was updated automatically but the package json was not updated https://github.com/microsoft/winget-pkgs/pull/28985

**Expected behavior**
Json file should be updated when the package PR is created

**Additional context**
https://github.com/vedantmgoyal2009/winget-pkgs-automation/blob/main/packages/b/balena.balenacli.json

**Comment by vedantmgoyal2009** [comment]
Oh, I was actually testing my modified script to ensure that there were no errors.

**Comment by Trenly** [comment]
> Also, I am thinking of removing JSON of packages whose repository is now read-only or packages that haven't been updated for more than two years since they would only eat my API limit.

Probably a good idea; Either that or add a parameter to the json file to skip updating them; That way we have a record that the packages were considered
