### ISSUE TITLE
[Bug]: YamlCreate is volatile and should be used inside of a try-catch block

### ISSUE THREAD

**Issue by Trenly** [vedantmgoyal2009/winget-pkgs-automation#122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Because YamlCreate is volatile, it should be used inside of a Try-Catch block to ensure that it doesn't terminate automation - https://github.com/vedantmgoyal2009/winget-pkgs-automation/runs/4001751560?check_suite_focus=true#step:3:759

https://github.com/vedantmgoyal2009/winget-pkgs-automation/blob/be2feefb5692eb492c8e9897a74cd4a217938e5f/scripts/SetupWorkingEnv.ps1#L59

**Comment by vedantmgoyal2009** [comment]
@Trenly Do you know how to convert "2021-11-02T20:06:34Z" to a human-readable time format? I've been wasting hours but could not find anything that could do this in PowerShell.

**Comment by Trenly** [comment]
> @Trenly Do you know how to convert "2021-11-02T20:06:34Z" to a human-readable time format? I've been wasting hours but could not find anything that could do this in PowerShell.
> 
> Edit: Found it. It was too simple. Just `[datetime]::Parse("2021-11-02T20:06:34Z")`

You can also use the .ToString() method with a [datetime format string](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings) like `$Date.ToString("hh:mm:ss.fff dd/MM/YYYY")`
