### ISSUE TITLE
[New Package]: Wondershare.Anireel

### ISSUE THREAD

**Issue by TaylorShi** [vedantmgoyal2009/winget-pkgs-automation#132]
### List the PackageIdentifier of the package to be added to automation

Wondershare.Anireel

### Details about the application

Anireel is an easy animated explainer video editor with rich ready-to-use assets that helps to effortlessly make animated videos for marketing, knowledge sharing, and eLearning. We make video animation easier to electrify features that satisfy your imagination!
 
You can do the following with an Anireel:
 
● Use rich ready-to-use assets like scenes, background, characters, props, text, and audio by easy drag and drop.
● Edit the assets, including modifying the size and colors and so on.
● Import video, audio, and images in various formats.
● Add enter & exit effects and motion path function to animate anything.
● Convert your text into vivid human dubbing through Text-to-Speech.
● Turn your scripts into animated videos with one click.
 
You will receive a free trial version for use after downloading and installing Wondershare Anireel. You can export videos with the Anireel watermark from the free plan.
After upgrading to the paid trial version, you can use all paid assets and export videos without a watermark.
 
And If you want to try the Text-to-Speech function, please purchase the TTS plan. You can get 200,000 Text-to-Speech characters for use per month.

**Comment by vedantmgoyal2009** [comment]
@allcontributors please add @TaylorShi for ideas
