### ISSUE TITLE
[New Package]: KDE.Kate

### ISSUE THREAD

**Issue by vedantmgoyal2009** [vedantmgoyal2009/winget-pkgs-automation#136]
### List the PackageIdentifier of the package to be added to automation

KDE.Kate

### Details about the application

1. https://binary-factory.kde.org/view/Windows%2064-bit/job/Kate_Release_win64/api/json?pretty=true
2. Invoke-RestMethod "$($x.lastSuccessfulBuild.url)api/json"
3. InstallerUrl: "$($x.lastSuccessfulBuild.url)artifact/$($y.artifacts.FileName -match $package.asset_regex)
4. PackageVersion - regex from $y.artifacts.FileName

Can also be used for KDE.KDEConnect

**Comment by jedieaston** [comment]
There's a really nice [Python library for Jenkins](https://jenkinsapi.readthedocs.io/en/latest/index.html), I was able to get all of the latest build info for the KDE projects in just a few minutes.

I know you're writing this in PowerShell, but it might be worth going through that library and seeing how they build their requests so you don't have to do regex.

**Comment by vedantmgoyal2009** [comment]
Actually, my school curriculum has Java, and I learnt some PowerShell while making contributions to YamlCreate. I'll add it to Extras so that in my free time, I would learn some Python and understand and try to implement it.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
My knowledge of PowerShell and Python has taught me that PowerShell is always better, so please do continue, @vedantmgoyal2009, not least because I shall be able to assist development of it significantly more easily if you do than I otherwise would, and winget is one of Microsoft's products.
