### ISSUE TITLE
[New Package]: Alibaba.Yuque

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal2009/winget-pkgs-automation#149]
### List the PackageIdentifier of the package to be added to automation

Alibaba.Yuque

### Details about the application

https://app.nlark.com/yuque-desktop/v2/latest-lark.json
```powershell
$result = (iwr 'https://app.nlark.com/yuque-desktop/v2/latest-lark.json' | ConvertFrom-Json).stable | Where-Object { $_.platform -eq 'win32' }
```

PackageVersion: `$result.version`
InstallerUrl: `$result.exe_url`

**Comment by vedantmgoyal2009** [comment]
Does it have any other source? It doesn't seem to be updated. We already have 0.9.31 in the repo, and the JSON still shows 0.9.30.

**Comment by SpecterShell** [comment]
You can leave this issue open and wait for the source get updated, or, turn to parse the download webpage.

https://github.com/TianXiaTech/scoop-txt/blob/master/bucket/yuque.json
https://github.com/chawyehsu/dorado/blob/master/bucket/yuque.json

Here are some examples. You can use the regex to match the version.
