### ISSUE TITLE
[New Package]: Cube.CubePlatform

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal2009/winget-pkgs-automation#156]
### List the PackageIdentifier of the package to be added to automation

Cube.CubePlatform

### Details about the application

https://infobox.cubejoy.com/data.ashx?JsonData={%22Code%22:%2210030%22}

PackageVersion: `$result.PackageVersion`
InstallerUrl 1: `https://appnews.cubejoy.com/app/$($version)/CubeSetup_v$($version).exe`
InstallerUrl 2: `https://newsapp.cubejoy.com/app/$($version)/CubeSetup_HK_TC_v$($version).exe`

**Comment by vedantmgoyal2009** [comment]
![image](https://user-images.githubusercontent.com/83997633/140616559-c83ef0b0-5c51-46da-a844-a43e8009fd85.png)

For version: `$result.result.version`
InstallerUrl1: `$result.result.mainland.downloadURL`
InstallerUrl2: `https://newsapp.cubejoy.com/app/$($version)/CubeSetup_HK_TC_v$($version).exe` (the one you suggested)

**Comment by SpecterShell** [comment]
The URLs need to be generated manually since the update API provides only one URL and lacks another one for zh-HK.

**Comment by vedantmgoyal2009** [comment]
> And the provided URL is in HTTP.

Ohh, sorry! I didn't notice that. BTW, the response I am getting is correct?

**Comment by SpecterShell** [comment]
Correct
