### ISSUE TITLE
[New Package]: Microsoft.Teams.*

### ISSUE THREAD

**Issue by vedantmgoyal2009** [vedantmgoyal2009/winget-pkgs-automation#157]
### List the PackageIdentifier of the package to be added to automation

Microsoft.Teams.*

### Details about the application

@ItzLevvie I remember, there were some scripts on https://github.com/ItzLevvie/MicrosoftTeams-msinternal, but I cannot find them now. Can you please share API or a link/source using which I can add Teams to my automation 🙏

**Comment by ItzLevvie** [comment]
For Continuous Deployment (CD) & Exploration builds, there's no public API - my code did a for loop:
```javascript
"use strict";

const https = require("https");

const enableLogging = false;

const getURL = "https://statics.teams.cdn.office.net";
const getPartialBuild = "1.4.00.";

const getPlatform = "win-x64";
const getPath = "production-windows-x64";
const getFile = "Teams_windows_x64.exe";

for (let getLatestBuild = 30951, getBuildLimit = getLatestBuild + 10; getLatestBuild <= getBuildLimit; getLatestBuild++) {
    https.get(getURL + "/" + getPath + "/" + getPartialBuild + getLatestBuild + "/" + getFile, (getResponse) => {
        if (getResponse.statusCode === 200) {
            const getDate = new Date(getResponse.headers["last-modified"]).toLocaleString("en-US", { dateStyle: "full", timeStyle: "short", timeZone: "PST" });
            const getMegabytes = Math.round(getResponse.headers["content-length"] / 1024 / 1024) + " MB";
            console.log(getPartialBuild + getLatestBuild + " (" + getPlatform + ") - published on " + getDate + " with " + getMegabytes + ": " + getURL + "/" + getPath + "/" + getPartialBuild + getLatestBuild + "/" + getFile);
        } else if (getResponse.statusCode === 404 && enableLogging) {
            console.log(getPartialBuild + getLatestBuild + " (" + getPlatform + "): Sorry, but an error has occurred as we cannot find this continuous deployment build of Microsoft Teams. Please try again later.");
        }
    }).on("error", () => {
        if (enableLogging) {
            console.log(getPartialBuild + getLatestBuild + " (" + getPlatform + "): Sorry, but an error has occurred as we cannot connect to the host. Please try again later.");
        }
    });
}

```

There's an API for Canary though:
https://config.teams.microsoft.com/config/v1/MicrosoftTeams/1415_1.0.0.0?environment=prod&audienceGroup=ring0&teamsRing=ring0&agent=TeamsBuilds

```javascript
"use strict";

const https = require("https");

const enableLogging = false;

const getURL = "https://statics.teams.cdn.office.net";

const getPlatform = "win-x64";
const getPath = "production-windows-x64";
const getFile = "Teams_windows_x64.exe";

https.get("https://config.teams.microsoft.com/config/v1/MicrosoftTeams/1415_1.0.0.0?environment=prod&audienceGroup=ring0&teamsRing=ring0&agent=TeamsBuilds", (getResponse) => {
    getResponse.on("data", (getData) => {
        try {
            if (getResponse.statusCode === 200) {
                const getBuild = JSON.parse(`${getData}`).BuildSettings.Desktop.windows64.latestVersion;
                https.get(getURL + "/" + getPath + "/" + getBuild + "/" + getFile, (getResponse) => {
                    if (getResponse.statusCode === 200) {
                        const getDate = new Date(getResponse.headers["last-modified"]).toLocaleString("en-US", { dateStyle: "full", timeStyle: "short", timeZone: "PST" });
                        const getMegabytes = Math.round(getResponse.headers["content-length"] / 1024 / 1024) + " MB";
                        console.log(getBuild + " (" + getPlatform + ") - published on " + getDate + " with " + getMegabytes + ": " + getURL + "/" + getPath + "/" + getBuild + "/" + getFile);
                    } else if (getResponse.statusCode === 404 && enableLogging) {
                        console.log(getPlatform + ": Sorry, but an error has occurred as we cannot find a preview build of Microsoft Teams. Please try again later.");
                    }
                }).on("error", () => {
                    if (enableLogging) {
                        console.log(getPlatform + ": Sorry, but an error has occurred as we cannot connect to the host. Please try again later.");
                    }
               });
            } else if (getResponse.statusCode === 404 && enableLogging) {
                console.log(getPlatform + ": Sorry, but an error has occurred as we cannot find a preview build of Microsoft Teams. Please try again later.");
            }
        } catch {}
    });
}).on("error", () => {
    if (enableLogging) {
        console.log(getPlatform + ": Sorry, but an error has occurred as we cannot connect to the host. Please try again later.");
    }
});
```


**Preview**:
https://teams.microsoft.com/desktopclient/installer/windows/x64?ring=ring3_6
https://teams.microsoft.com/desktopclient/installer/windows/x32?ring=ring3_6
https://teams.microsoft.com/desktopclient/installer/windows/arm64?ring=ring3_6

_To get MSI installers, replace `.exe` with `.msi`._

**Production**:
https://teams.microsoft.com/desktopclient/installer/windows/x64?ring=general
https://teams.microsoft.com/desktopclient/installer/windows/x32?ring=general
https://teams.microsoft.com/desktopclient/installer/windows/arm64?ring=general

_To get MSI installers, replace `.exe` with `.msi`._

**Comment by ItzLevvie** [comment]
I reuploaded the source code: https://github.com/ItzLevvie/MicrosoftTeams-msinternal/commit/0d8e730bbe56a934a9d98c28f95fe7c51d0a00d9

**Comment by vedantmgoyal2009** [comment]
@ItzLevvie How do you differentiate b/w CDand Exploration builds?

**Comment by ItzLevvie** [comment]
> @ItzLevvie How do you differentiate b/w CD and Exploration builds?

If you understand the build number format below it may or may not be tricky, since there's no public API to work with, I usually add 100 to the build number every day to CD and 50 for Exploration.

e.g. Thursday, 4th of November 2021 for CD would be 1.4.00.30851 and above (as long as it's below 1.4.00.30899), and 1.4.00.30801 and above (as long as it's below 1.4.00.30849) for Exploration.
e.g. Friday, 5th of November 2021 for CD would be 1.4.00.30951 and above (as long as it's 1.4.00.30999), and 1.4.00.30801 and above (as long as it's below 1.4.00.30849) for Exploration.

Sometimes the Microsoft Teams team doesn't compile Saturday and Sunday builds so we jump by 300 to skip Saturday and Sunday in the build number.
e.g. Monday, 8th of November 2021 for CD would be 1.4.00.31251 and above (as long as it's below 1.4.00.31299), and 1.4.00.31201 and above (as long as it's below 1.4.00.31249) for Exploration.

Current Build Number format:
1.4.0.0.XXX51 to 1.4.0.0.XXX99 = Starts off from Continuous Deployment (CD) -> One (or Multiple) build(s) is chosen from Continuous Deployment (CD) to be pushed to Preview and then to Production.
1.4.0.0.XXX01 to 1.4.0.0.XXX49 = Exploration (i.e. when you install the app, there should be -E in the version in the 3 horizontal menu in Microsoft Teams)

1.1.0.0.XXXXX = 2018 builds
1.2.0.0.XXXXX = 2019 builds
1.3.0.0.XXXXX = 2020 builds
1.4.0.0.XXXXX = 2021 builds
1.5.0.0.XXXXX (?) = 2022 builds

**Comment by vedantmgoyal2009** [comment]
@ItzLevvie Was the PR opened for Teams Exploration was correct? Also, please correct me if I am doing anything wrong [here](https://raw.githubusercontent.com/vedantmgoyal2009/winget-pkgs-automation/main/package_scripts/m/microsoft.teams.exploration.ps1).

**Comment by ItzLevvie** [comment]
> Was the PR opened for Teams Exploration correct?

Looks good, but it seems to be stuck on 311XX?

Current builds for Exploration and CD are on 315XX.

**Comment by vedantmgoyal2009** [comment]
I changed the cron from '0 */2 * * *' to ' 0 * * * *'. So it might be that due to this, the builds are lagging behind.

**Comment by vedantmgoyal2009** [comment]
@ItzLevvie Should we keep about only the last X versions since Exploration and CD builds are released almost daily (like daily builds) and hence there would be many many many versions in the repository which may not be much useful.

**Comment by ItzLevvie** [comment]
> @ItzLevvie Should we keep about only the last X versions since Exploration and CD builds are released almost daily (like daily builds) and hence there would be many many many versions in the repository which may not be much useful.

Sure.
