### ISSUE TITLE
[Feature/Idea]: Support for REST sources

### ISSUE THREAD

**Issue by vedantmgoyal2009** [vedantmgoyal2009/winget-pkgs-automation#161]
### What would you like to see changed/added?

This may need a lot of work but I'm planning to add support for WinGet REST sources. I'm going to look at +1s and if it gains some importance, I would plan to do so.

**Comment by vedantmgoyal2009** [comment]
@jedieaston I don't know if it would be a good decision but I'm planning to transform this into a GitHub Action so that users who are using their own source for winget, they can use this action to keep packages up-to-date in their GitHub repository.

I'm planning to take the following inputs:
```
repo: <in the format of owner/repo>
in-place-upgrade: true or false (if user doesn't want to keep old manifests)
packages: * (for all), <array> (if a user wants to upgrade selected packages)
```

**Comment by jedieaston** [comment]
You'll need write access to their repositories, I don't know if this is feasible. Most of them will be sitting behind corporate firewalls or whatever. 

They can just `git fetch` winget-pkgs, right?

**Comment by vedantmgoyal2009** [comment]
Well, I'll try to keep most of the things as customizable as I can. I can make the bot commit the new manifests directly or instead, open PRs as we do for community repo. The limitation would be that the source will have to follow the same PackageIdentifier as of the community repo.

**Comment by jedieaston** [comment]
Most REST sources will not have a Git repository at all, since they don't need one (I mean, yes, they should be putting manifests in version control but they probably won't). You add manifests to rest sources via POST and PUT requests to the endpoints. I don't know if that makes sense for this project or not.

**Comment by vedantmgoyal2009** [comment]
> Most REST sources will not have a Git repository at all

If that's so, it doesn't make sense to convert into a GitHub action just for the community repo. Even, if there would be one or two sources hosted on GitHub, they would most probably be managed and automated by themselves. 

> You add manifests to rest sources via POST and PUT requests to the endpoints

Is that what Publish Pipeline does on the community repo and is it the reason why multiple manifests/changes aren't supported in one PR?

**Comment by jedieaston** [comment]
No, the community repo doesn't use a REST source, it uses a pre-indexed source (which is a SQLite file). The publishing pipeline converts the YAML files in the community repo into a SQLite file with the proper schema, packages it as an appx, signs it, and publishes it to somewhere in Azure. Then when you run `winget source update` you get the latest appx file and all of the updates to the community repo.
