### ISSUE TITLE
[New Package]: Streamlabs.StreamlabsOBS

### ISSUE THREAD

**Issue by OfficialEsco** [vedantmgoyal2009/winget-pkgs-automation#170]
### List the PackageIdentifier of the package to be added to automation

Streamlabs.StreamlabsOBS

### Details about the application

Get releases from https://github.com/stream-labs/streamlabs-obs/tags
Extract version from tag_name
InstallerUrl: https://slobs-cdn.streamlabs.com/Streamlabs+OBS+Setup+$($version).exe

**Comment by vedantmgoyal2009** [comment]
@all-contributors please add @OfficialEsco for ideas
