### ISSUE TITLE
[New Package]: Elgato.StreamDeck

### ISSUE THREAD

**Issue by hmmwhatsthisdo** [vedantmgoyal2009/winget-pkgs-automation#178]
### List the PackageIdentifier of the package to be added to automation

Elgato.StreamDeck

### Details about the application

Currently, Elgato's packages on WinGet need to be manually updated. I don't have the hardware to test the remainder of the packages, but after doing a little debugging of the StreamDeck application it appears that the auto-updater is implemented by GETting `https://gc-updates.elgato.com/windows/sd-update/final/app-version-check.json`, which then contains keys for binaries to deliver for automatic and manually-initiated updates.

It looks like there's both: 
* A static path to the latest MSI (`https://gc-updates.elgato.com/windows/sd-update/final/app-download-automatic.php` or `<...>/app-download-manual.php`)
* A link to the MSI on Elgato's CDN (the static paths just 302 to an MSI)

The "official" external download method is to visit https://www.elgato.com/en/downloads, which GETs `https://www.elgato.com/sites/default/files/downloads.json` - there's some keys for each of Elgato's software downloads there; overall structure is similar.

**Comment by vedantmgoyal2009** [comment]
@allcontributors please add @hmmwhatsthisdo for ideas

**Comment by hmmwhatsthisdo** [comment]
@vedantmgoyal2009 If it helps, I can maybe take a shot at adding a script to poll/parse Elgato's site for StreamDeck info (as that's probably the most "correct") - however it looks like the version tags listed in the JSON don't include the build number (just major.minor.revision). 

I'm not sure if there's precedent on how to best tackle this - I can just fall back to using the update API endpoint, but that won't necessarily work for other Elgato software.

**Comment by vedantmgoyal2009** [comment]
`https://www.elgato.com/sites/default/files/downloads.json` is completely fine and can be used for StreamDeck, as well as for other packages too.
- `Elgato.4KCaptureUtility`
- `Elgato.ControlCenter`
- `Elgato.EpocCam`
- `Elgato.GameCapture.HD`
- `Elgato.StreamDeck` (this one)
- `Elgato.WaveLink`

You indirectly requested 5 other packages with this which is highly appreciated 🎉. I'll be free after mid-December, then I'll add all the packages. This month, I've my exams so I'll be a little busy but I keep checking GitHub at least once every 3-4 days to at least keep a track of what's going on.
