### ISSUE TITLE
Some new things to be implemented [New Feature]

### ISSUE THREAD

**Issue by vedantmgoyal2009** [vedantmgoyal2009/winget-pkgs-automation#18]
**Describe the feature/enhancement you'd like**
- Support for auto-updating packages from SourceForge [**DONE**] - e.g. Freeplane
- Support for auto-updating packages from RSS feeds.
- Check if a PR has been opened before submitting Pull Request via automation [**DONE**] - Implemented in YamlCreate.ps1 Trenly/winget-pkgs#69

**Proposed technical implementation details (optional)**
Found a way, will be implementing soon.

**Additional context**
https://gist.github.com/OfficialEsco/599257140346fa4a79b36dc63bb20d61 (from https://github.com/vedantmgoyal2009/winget-pkgs-automation/issues/1#issuecomment-927286125)

**Comment by vedantmgoyal2009** [comment]
> Check if a PR has been opened before submitting Pull Request via automation.

Implemented in YamlCreate.ps1 itself - https://github.com/Trenly/winget-pkgs/pull/69

**Comment by jedieaston** [comment]
You'll probably have to poll the RSS feeds and [trigger the Action on a new entry](https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event). You could use a cron trigger on another Action to run every couple hours and check the RSS feeds for new entries, and if it finds something, then fire the action to submit a PR.

**Comment by felipecrs** [comment]
BTW, I may be wrong, but I believe that if you use a token for authenticating against the GitHub API (if not already), the limit of the requests may increase.

**Comment by vedantmgoyal2009** [comment]
@felipecrs I am already using a token in the header: https://github.com/vedantmgoyal2009/winget-pkgs-automation/blob/main/automation.ps1#L45

**Comment by jedieaston** [comment]
You'd only run the search when you detected that there isn't an up-to-date manifest merged already. It's possible that you'd hit 30 of those in a minute, but if you're running this only every hour or so, I kind of doubt it. 

(Perhaps someone has a better idea).

**Comment by felipecrs** [comment]
Oh, I see. And thanks for the reference.

**Comment by vedantmgoyal2009** [comment]
@jedieaston I am going to test the logic implemented by Trenly for checking existing PRs in YamlCreate. I think it would work perfectly.

**Comment by vedantmgoyal2009** [comment]
@jedieaston do you have any packages that have RSS feeds?

**Comment by jedieaston** [comment]
I've used RSS with GitHub Releases and with the JetBrains releases blog. But both of those have APIs (jetbrains is undocumented, you'll have to look at Evergreen to see how to do that), so I don't know if I'd do that. 

SourceForge has RSS feeds for repos as well (I haven't messed with them).

**Comment by vedantmgoyal2009** [comment]
> (jetbrains is undocumented, you'll have to look at Evergreen to see how to do that)

@jedieaston I'm not familiar with Evergreen. Can you please tell me a bit more about that?

Another question: Does RSS with GitHub releases contain pre-releases?

**Comment by vedantmgoyal2009** [comment]
With the support of **individual package scripts**, searching through RSS feeds can be implemented. Hence, closing this issue.
