### ISSUE TITLE
[New Package]: Jellyfin.JellyfinServer

### ISSUE THREAD

**Issue by laedit** [vedantmgoyal2009/winget-pkgs-automation#180]
### List the PackageIdentifier of the package to be added to automation

Jellyfin.JellyfinServer

### Details about the application

The latest stable version downloads are only available [here](https://repo.jellyfin.org/releases/server/windows/stable/), despite the project being on github.
The installer url and version can be retrieved with these lines:
```bash
$r=iwr https://repo.jellyfin.org/releases/server/windows/stable/ -UseBasicParsing 
$installerUrl = "https://repo.jellyfin.org/releases/server/windows/stable/$($r.Links | ?{$_.href -match "installer\/jellyfin_(.*)_windows-x64\.exe$"} | select -ExpandProperty HREF)"
$version = $Matches[1]
```
I'd be happy to propose a PR if you like, if I understand well I have to add new files in packages and packages_script folder?

**Comment by vedantmgoyal2009** [comment]
> I'd be happy to propose a PR if you like, if I understand well I have to add new files in packages and packages_script folder?

Sure, go ahead. I will make corrections if anything goes wrong.
