### ISSUE TITLE
[New Package]: PTRTECH.UVtools

### ISSUE THREAD

**Issue by Trenly** [vedantmgoyal2009/winget-pkgs-automation#217]
### List the PackageIdentifier of the package to be added to automation

PTRTECH.UVtools

### Details about the application

https://github.com/microsoft/winget-pkgs/pull/38685
https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+uvtools

https://github.com/sn4k3/UVtools

**Comment by vedantmgoyal2009** [comment]
I guess it has already been automated by the developer.

GitHub Workflow: https://github.com/sn4k3/UVtools/blob/master/.github/workflows/WingetAutoSubmit.yml
