### ISSUE TITLE
[New Package]: Fiddler Everywhere Beta

### ISSUE THREAD

**Issue by ItzLevvie** [vedantmgoyal2009/winget-pkgs-automation#223]
### List the PackageIdentifier of the package to be added to automation

Telerik.Fiddler.Everywhere.Beta

### Details about the application

https://api.getfiddler.com/win/beta

**Comment by rosen-vladimirov** [comment]
Hey @ItzLevvie , @vedantmgoyal2009 ,
I'm one of the authors of Fiddler Everywhere and I suggest disregarding this request.
Fiddler Everywhere's beta version is just for testing purposes and should not be used in any customer's context. In fact, in many cases the beta version does not contain a lot of functionalities that are included in the current live version. We have this "beta" only for automated testing of a specific use-case, for which it is not required to have up-to-date code in the version that is downloaded.
So, I strongly recommend to skip adding of this package.

**Comment by vedantmgoyal2009** [comment]
Ok, can I add Insiders and Internal versions?

**Comment by rosen-vladimirov** [comment]
@vedantmgoyal2009  I recommend using only the latest official version, which can be downloaded directly from our [website](https://www.telerik.com/download/fiddler-everywhere).
In terms of automatic updates and redistribution, our [End User License Agreement](https://www.telerik.com/purchase/license-agreement/fiddler-everywhere) has some limitations, so my recommendation is to check it with your legal advisors and see if the current suggestion for automatic redistribution of updates is allowed.
I strongly recommend to stick to the official download way through our [website](https://www.telerik.com/download/fiddler-everywhere). If you have some troubles with it, you can send us a support ticket (there's a support link in the product).

**Comment by vedantmgoyal2009** [comment]
@ItzLevvie So should we remove Beta, Insider and Internal versions from the repo?

**Comment by vedantmgoyal2009** [comment]
> @ItzLevvie So should we remove Beta, Insider and Internal versions from the repo?

cc @ItzLevvie

**Comment by ItzLevvie** [comment]
I took a look at it.

It seems like Beta and Internal can be removed because it doesn't get regular updates by the publisher; but Insiders does according to https://github.com/telerik/fiddler-everywhere-docs/commit/08a047e604f067a5f269ec80c4f2f5e4b9a197db.

**Comment by vedantmgoyal2009** [comment]
@ItzLevvie I have opened PRs for removing Beta and Internal versions of Fiddler Everywhere.
