### ISSUE TITLE
[New Package]: Fiddler Everywhere Internal

### ISSUE THREAD

**Issue by ItzLevvie** [vedantmgoyal2009/winget-pkgs-automation#225]
### List the PackageIdentifier of the package to be added to automation

Telerik.Fiddler.Everywhere.Internal

### Details about the application

https://api.getfiddler.com/win/internal

**Comment by vedantmgoyal2009** [comment]
* Closed due to discussion on https://github.com/vedantmgoyal2009/winget-pkgs-automation/issues/223
