### ISSUE TITLE
[New Package]: ByteDance.Feishu

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal2009/winget-pkgs-automation#231]
### List the PackageIdentifier of the package to be added to automation

ByteDance.Feishu

### Details about the application

https://www.feishu.cn/api/downloads

PackageVersion: `$result.versions.Windows.version_number`
InstallerUrl: `$result.versions.Windows.download_link`

**Comment by SpecterShell** [comment]
![image](https://user-images.githubusercontent.com/56779163/150683780-bc264dc9-8a59-45fa-92f8-0a3cfa9763f2.png)

**Comment by vedantmgoyal2009** [comment]
@SpecterShell I'm working on AutomationV2, hopefully, all the errors will be fixed soon since I'll be re-adding the packages to the automation.

**Comment by vedantmgoyal2009** [comment]
Fixed in Automation v2.0.0.
