### ISSUE TITLE
[New Package]: EaseUS.PartitionMaster

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal2009/winget-pkgs-automation#250]
### List the PackageIdentifier of the package to be added to automation

EaseUS.PartitionMaster

### Details about the application

https://download.easeus.com/api/index.php/Home/Index/productInstall?pid=5&version=free

PackageVersion: `$result.data.curNum`
InstallerUrl: `$result.data.download3` (`download` and `download2` are also OK)

**Comment by vedantmgoyal2009** [comment]
For future, please also link a PR for the package, it would easy for me to add the package to the automation.
