### ISSUE TITLE
[New Package]: Baulk.Baulk

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal2009/winget-pkgs-automation#261]
### List the PackageIdentifier of the package to be added to automation

Baulk.Baulk

### Details about the application

https://github.com/baulk/baulk/releases

**Comment by SpecterShell** [comment]
Ongoing pull request:
https://github.com/microsoft/winget-pkgs/pull/41683

**Comment by vedantmgoyal2009** [comment]
Anyway to get 3.0.0.**xxx** part?

**Comment by SpecterShell** [comment]
I haven't seen any `3.0.0.xxx` in installer filenames. Only zip archives have that.

**Comment by vedantmgoyal2009** [comment]
Then this will have to wait until the automation supports getting version from ARP Entries by installing the package first in the GitHub runner itself.

**Comment by SpecterShell** [comment]
I thought you are talking about file names from GitHub releases...
```PowerShell
(Get-Item .\BaulkSetup-x64.exe).VersionInfo.ProductVersion
```

**Comment by vedantmgoyal2009** [comment]
That will work though🎉
