### ISSUE TITLE
[New Package]: BBC.iPlayer

### ISSUE THREAD

**Issue by quhxl** [vedantmgoyal2009/winget-pkgs-automation#288]
### List the PackageIdentifier of the package to be added to automation

BBC.iPlayer

### Details about the application

`$result = (Invoke-WebRequest -Uri 'https://downloads-app.iplayer.api.bbc.co.uk/stable/win32-x64' -Method Head).BaseResponse.RequestMessage.RequestUri.OriginalString`
`
$version = ($result | Select-String -Pattern '[0-9.]{3,}.*(?=\.)').Matches.Value
`

**Comment by vedantmgoyal2009** [comment]
@allcontributors please add @quhxl for ideas
