### ISSUE TITLE
[New Package]: Microsoft Edge (all)

### ISSUE THREAD

**Issue by vedantmgoyal9** [vedantmgoyal2009/winget-pkgs-automation#36]
### List the PackageIdentifier of the package to be added to automation

Microsoft.Edge*

**Comment by vedantmgoyal2009** [comment]
@jedieaston since you update MS edge every time (https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+edge+is%3Aclosed), I would like to tell you that it is also automated now.

**Comment by jedieaston** [comment]
Is this what it feels like to be automated out of a job 😂

Thanks!
