### ISSUE TITLE
[New Package]: Baidu.BaiduNetdisk

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal2009/winget-pkgs-automation#64]
### List the PackageIdentifier of the package to be added to automation

Baidu.BaiduNetdisk

### Details about the application

Source:
https://pan.baidu.com/disk/cmsdata?do=client

`$result.guanjia.url` InstallerUrl
`$result.guanjia.version` PackageVersion (Regex or slicing is needed for parsing)

**Comment by SpecterShell** [comment]
3 versions missed:
https://github.com/microsoft/winget-pkgs/pull/41645
https://github.com/microsoft/winget-pkgs/pull/41646
https://github.com/microsoft/winget-pkgs/pull/41647

**Comment by vedantmgoyal2009** [comment]
Fixed in Automation v2.0.0.
