### ISSUE TITLE
[Potential Bug]: Tag names may not be sanitized for comparison

### ISSUE THREAD

**Issue by Trenly** [vedantmgoyal2009/winget-pkgs-automation#81]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the automation, the tag is being explicitly compared to see if it is greater than the previously checked tag to determine if an update is needed. However, it isn't guaranteed that the tag will be sanitized for the comparison.

Consider the example:
```
LastCheckedTag: v2.0.1
Tag: 3.0.0
```
Something as simple as a repository owner forgetting a character can lead to versions being missed. However, since the package could use `result.tag_name.TrimStart('v')` to get the version, there isn't a reason that it should be missed.

# Potential Fix
Instead of the last checked tag, fetch and store the last checked release ID (`result.id`). Since this is autogenerated by github, it is should always be greater for newer releases. The tag can still be used to fetch the version number, but doesn't need to be stored

I know this won't work for the custom script packages and non-git packages, but there the version can be used instead still

**Comment by vedantmgoyal2009** [comment]
This is a good issue + fix. I have recently seen issues with Jackett which the automation failed to update when it's tag got updated from `v0.18.995` to `v0.18.1001`. I've prepared for migration from `tag_name` to `release id` and I hope that will work perfectly.
